### ISSUE TITLE
connect problem

### ISSUE THREAD

**Issue by wuladapang** [keyvanarasteh/darkwebcrawler#1]
!!! ERROR : , error : SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x0000028972313160>: Failed to establish a new connection: 0x06: TTL expired'))

!!! Stopping project ...
after connection，it shows that.

**Comment by keyvanarasteh** [comment]
u must run Tor Browser to serve its connection. 
as u can see max retries exceed.

problem is TOR Bridge, sry 4 late answer
